images:
  image:
    repository: ghcr.io/chrislongros/anki-sync-server-enhanced
    tag: 25.09.2
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  anki_container_name: anki
  perms_container_name: permissions
