images:
  image:
    repository: ghcr.io/thephaseless/byparr
    tag: 2.1.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  byparr_container_name: byparr
  perms_container_name: permissions
