images:
  image:
    repository: ghcr.io/plankanban/planka
    tag: "2.0.0"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_15_image:
    repository: postgres
    tag: 15.16-bookworm
  postgres_17_image:
    repository: postgres
    tag: 17.8-bookworm
  postgres_18_image:
    repository: postgres
    tag: 18.2-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.1.7

consts:
  planka_container_name: planka
  migration_container_name: migration
  perms_container_name: permissions
  postgres_container_name: postgres
  db_user: planka
  db_name: planka
