images:
  image:
    repository: fireflyiii/core
    tag: version-6.4.22
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  importer_image:
    repository: fireflyiii/data-importer
    tag: version-2.1.0
  postgres_15_image:
    repository: postgres
    tag: 15.16-bookworm
  postgres_17_image:
    repository: postgres
    tag: 17.8-bookworm
  postgres_18_image:
    repository: postgres
    tag: 18.2-trixie
  redis_image:
    repository: valkey/valkey
    tag: 9.0.2
  alpine_image:
    repository: alpine
    tag: "3.23.3"
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.1.7

consts:
  firefly_iii_container_name: firefly-iii
  firefly_iii_importer_container_name: importer
  firefly_iii_cron_container_name: cron
  perms_container_name: permissions
  postgres_container_name: postgres
  redis_container_name: redis
  db_user: firefly
  db_name: firefly
  run_as_user: 33
  run_as_group: 33
  internal_web_port: 8080
