resources:
  limits:
    cpus: 2.0
    memory: 4096

planka:
  postgres_image_selector: postgres_18_image
  db_password: db-planka-password
  secret_key: secret-key
  default_admin_email: admin@planka.com
  default_admin_name: admin-planka
  default_admin_username: admin-planka
  default_admin_password: admin-planka-password
  base_url: http://localhost:8080
  trust_proxy: false
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 8080

run_as:
  user: 568
  group: 568

ix_volumes:
  data: /opt/tests/mnt/planka/data
  logs: /opt/tests/mnt/planka/logs
  postgres_data: /opt/tests/mnt/planka/postgres-data

  # Deprecated Volumes
  avatars: /opt/tests/mnt/planka/avatars
  background_images: /opt/tests/mnt/planka/background-images
  attachments: /opt/tests/mnt/planka/attachments

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  logs:
    type: ix_volume
    ix_volume_config:
      dataset_name: logs
      create_host_path: true
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: postgres_data
      create_host_path: true

  # Deprecated Volumes
  avatars:
    type: ix_volume
    ix_volume_config:
      dataset_name: avatars
      create_host_path: true
  background_images:
    type: ix_volume
    ix_volume_config:
      dataset_name: background_images
      create_host_path: true
  attachments:
    type: ix_volume
    ix_volume_config:
      dataset_name: attachments
      create_host_path: true
  additional_storage: []
