images:
  image:
    repository: mostafawahied/autoxpose
    tag: 0.4.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  autoxpose_container_name: autoxpose
  perms_container_name: permissions
  data_path: /app/packages/backend/data
