images:
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: v0.8.2
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  ollama_image:
    repository: ghcr.io/open-webui/open-webui
    tag: v0.8.2-ollama
  cuda_image:
    repository: ghcr.io/open-webui/open-webui
    tag: v0.8.2-cuda
  redis_image:
    repository: valkey/valkey
    tag: 9.0.2

consts:
  open_webui_container_name: open-webui
  redis_container_name: redis
  perms_container_name: permissions
