resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: Etc/UTC

dispatcharr:
  postgres_image_selector: postgres_18_image
  db_password: dispatcharr-db-pass
  redis_password: dispatcharr-redis-pass
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 8080

run_as:
  user: 568
  group: 568

ix_volumes:
  data: /opt/tests/mnt/dispatcharr/data
  postgres-data: /opt/tests/mnt/dispatcharr/postgres-data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: postgres-data
      create_host_path: true
  additional_storage: []
