{% from "macros/migration.sh" import migration %}
{% set tpl = ix_lib.base.render.Render(values) %}

{% if values.planka.postgres_image_selector == "postgres_15_image" %}
  {% do tpl.notes.add_deprecation("Postgres 15 is deprecated and will be removed in the near future. Please upgrade.") %}
{% endif %}

{% if not values.storage.remove_deprecated_storage %}
  {% do tpl.notes.add_deprecation(
    "Avatars, Background Images and Attachments storages are deprecated (and no longer used) and will be removed in the near future. "
    "Edit the application and enable the Remove Deprecated Storage option to remove them. "
    "All data previously in the deprecated storage should be already copied to the new Data storage, "
    "by the automatic migration process. Note that by default the Data Storage points to an iX Volume, "
    "if you want to use a Host Path, you need to stop the application, move the data from the iX Volume "
    "to the Host Path and then edit the application to point to the Host Path."
  ) %}
{% endif %}

{% set c1 = tpl.add_container(values.consts.planka_container_name, "image") %}
{% set mig = tpl.add_container(values.consts.migration_container_name, "image") %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.run_as.user, "gid": values.run_as.group, "mode": "check"} %}

{% set pg_config = {
  "user": values.consts.db_user,
  "password": values.planka.db_password,
  "database": values.consts.db_name,
  "volume": values.storage.postgres_data,
} %}
{% set postgres = tpl.deps.postgres(values.consts.postgres_container_name, values.planka.postgres_image_selector, pg_config, perm_container) %}

{% for c in [c1, mig] %}
  {% do c.set_user(values.run_as.user, values.run_as.group) %}
  {% do c.depends.add_dependency(values.consts.postgres_container_name, "service_healthy") %}

  {% do c.environment.add_env("NODE_ENV", "production") %}
  {% do c.environment.add_env("BASE_URL", values.planka.base_url.rstrip("/")) %}
  {% do c.environment.add_env("TRUST_PROXY", values.planka.trust_proxy) %}
  {% do c.environment.add_env("PORT", values.network.web_port.port_number) %}
  {% do c.environment.add_env("SECRET_KEY", values.planka.secret_key) %}
  {% do c.environment.add_env("DATABASE_URL", postgres.get_url("postgresql")) %}
  {% if values.planka.default_admin_email %}
    {% do c.environment.add_env("DEFAULT_ADMIN_EMAIL", values.planka.default_admin_email) %}
    {% do c.environment.add_env("DEFAULT_ADMIN_NAME", values.planka.default_admin_name) %}
    {% do c.environment.add_env("DEFAULT_ADMIN_USERNAME", values.planka.default_admin_username) %}
    {% do c.environment.add_env("DEFAULT_ADMIN_PASSWORD", values.planka.default_admin_password) %}
  {% endif %}
  {% do c.environment.add_user_envs(values.planka.additional_envs) %}

  {% do c.add_storage("/app/data", values.storage.data) %}
  {% do c.add_storage("/app/logs", values.storage.logs) %}
  {% do c.add_storage("/app/.tmp", {"type": "tmpfs", "tmpfs_config": {"size": 20, "uid": values.run_as.user, "gid": values.run_as.group}}) %}

  {% for store in values.storage.additional_storage %}
    {% do c.add_storage(store.mount_path, store) %}
  {% endfor %}
{% endfor %}

{% do mig.setup_as_helper(disable_network=false) %}
{% do mig.configs.add("migration.sh", migration(values), "/migration.sh", "0755") %}
{% do mig.set_entrypoint(["/bin/sh", "/migration.sh"]) %}
{% do mig.add_storage("/app/public/user-avatars", values.storage.avatars) %}
{% do mig.add_storage("/app/public/project-background-images", values.storage.background_images) %}
{% do mig.add_storage("/app/private/attachments", values.storage.attachments) %}
{% do perm_container.add_or_skip_action("attachments", values.storage.attachments, perms_config) %}
{% do perm_container.add_or_skip_action("user-avatars", values.storage.avatars, perms_config) %}
{% do perm_container.add_or_skip_action("project-background-images", values.storage.background_images, perms_config) %}

{% do perm_container.add_or_skip_action("logs", values.storage.logs, perms_config) %}
{% do perm_container.add_or_skip_action("data", values.storage.data, perms_config) %}
{% for store in values.storage.additional_storage %}
  {% do perm_container.add_or_skip_action(store.mount_path, store, perms_config) %}
{% endfor %}

{% do c1.depends.add_dependency(values.consts.migration_container_name, "service_completed_successfully") %}
{% do c1.healthcheck.set_test("wget", {"port": values.network.web_port.port_number}) %}
{% do c1.add_port(values.network.web_port) %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do c1.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
  {% do mig.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
  {% do postgres.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.portals.add(values.network.web_port) %}

{{ tpl.render() | tojson }}
