images:
  image:
    repository: ghcr.io/hargata/lubelogger
    tag: v1.6.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_18_image:
    repository: postgres
    tag: 18.2-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.1.7

consts:
  lubelogger_container_name: lubelogger
  postgres_container_name: postgres
  perms_container_name: permissions
  db_user: lubelogger
  db_name: lubelogger
