images:
  image:
    repository: sctx/overseerr
    tag: 1.35.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  perms_container_name: permissions
  overseerr_container_name: overseerr
