images:
  image:
    repository: ghcr.io/cleanuparr/cleanuparr
    tag: 2.6.2
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  cleanuparr_container_name: cleanuparr
  perms_container_name: permissions
