images:
  image:
    repository: roundcube/roundcubemail
    tag: 1.6.13-apache
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_15_image:
    repository: postgres
    tag: 15.16-bookworm
  postgres_17_image:
    repository: postgres
    tag: 17.8-bookworm
  postgres_18_image:
    repository: postgres
    tag: 18.2-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.1.7

consts:
  roundcube_container_name: roundcube
  perms_container_name: permissions
  postgres_container_name: postgres
  internal_web_port: 80
  db_user: roundcube
  db_name: roundcube
