{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.npmplus_container_name, "image") %}

{% do c1.add_caps(["SETUID", "SETGID", "CHOWN", "FOWNER", "DAC_OVERRIDE"]) %}
{% do c1.healthcheck.set_custom_test(["CMD", "healthcheck.sh"]) %}
{% do c1.add_extra_host("host.docker.internal", "host-gateway") %}
{% do c1.environment.add_env("DISABLE_HTTP", values.network.http_port.bind_mode == "") %}
{% do c1.environment.add_env("HTTP_PORT", values.network.http_port.port_number) %}
{% do c1.environment.add_env("HTTPS_PORT", values.network.https_port.port_number) %}
{% do c1.environment.add_env("NPM_PORT", values.network.web_port.port_number) %}
{% do c1.environment.add_user_envs(values.npmplus.additional_envs) %}

{% do c1.add_port(values.network.web_port) %}
{% do c1.add_port(values.network.http_port) %}
{% do c1.add_port(values.network.https_port) %}
{% do c1.add_port(values.network.https_port, {"protocol":"udp"}) %}
{% for port in values.network.additional_ports %}
  {% do c1.add_port(port) %}
{% endfor %}

{% do c1.add_storage(values.consts.data_path, values.storage.data) %}
{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
{% endfor %}

{% do tpl.portals.add(values.network.web_port) %}
{% do tpl.notes.set_body(values.consts.notes_body) %}

{{ tpl.render() | tojson }}
